apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-app-config
  namespace: {{ .Values.namespace }}

data:
  REDIS_HOST: {{ .Values.redis.serviceName | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}