apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: voting-db
    creationPolicy: Owner

  data:

    - secretKey: DB_HOST
      remoteRef:
        key: project2-ruoxihou/rds/postgres
        property: host

    - secretKey: DB_PORT
      remoteRef:
        key: project2-ruoxihou/rds/postgres
        property: port

    - secretKey: DB_USERNAME
      remoteRef:
        key: project2-ruoxihou/rds/postgres
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: project2-ruoxihou/rds/postgres
        property: password

    - secretKey: DB_NAME
      remoteRef:
        key: project2-ruoxihou/rds/postgres
        property: database