name: CD Pipeline
 
on:
  workflow_run:
    workflows: ["CI Pipeline for Docker Images"]
    types: ["completed"]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
 
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
 
      - name: Deploy Docker containers on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            # Pull latest images
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:v1.0.0
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/worker-app:v1.0.0
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/result-app:v1.0.0
 
            # Create a Docker network (if not already created)
            sudo docker network create voting-app || true
 
            # Run Vote App
            sudo docker run -d --name voting-app --network voting-app -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:v1.0.0

            # Run Worker App
            sudo docker run -d --name worker-app --network voting-app ${{ secrets.DOCKERHUB_USERNAME }}/worker-app:v1.0.0

            # Run Result App
            sudo docker run -d --name result-app --network voting-app -p 5001:5001 ${{ secrets.DOCKERHUB_USERNAME }}/result-app:v1.0.

            # Run Redis
            sudo docker run -d --name redis --network voting-app redis:alpine

      - name: 
