[bastion]
bastion-a az=az1
bastion-c az=az2

[frontend]
frontend-a az=az1 private_ip=10.5.1.212 private_dns=ip-10-5-1-212.us-west-2.compute.internal redis_host_ip=10.5.2.209 result_db_host_ip=10.5.2.244
frontend-c az=az2 private_ip=10.5.3.7 private_dns=ip-10-5-3-7.us-west-2.compute.internal redis_host_ip=10.5.4.175 result_db_host_ip=10.5.4.236

[middleware]
middleware-b az=az1 private_ip=10.5.2.209 private_dns=ip-10-5-2-209.us-west-2.compute.internal postgres_primary_ip=10.5.2.244
middleware-d az=az2 private_ip=10.5.4.175 private_dns=ip-10-5-4-175.us-west-2.compute.internal postgres_primary_ip=10.5.2.244

[postgres_primary]
db-1 az=az1 private_ip=10.5.2.244 private_dns=ip-10-5-2-244.us-west-2.compute.internal postgres_role=primary

[postgres_standby]
db-2 az=az2 private_ip=10.5.4.236 private_dns=ip-10-5-4-236.us-west-2.compute.internal postgres_role=standby postgres_primary_ip=10.5.2.244

[postgres:children]
postgres_primary
postgres_standby

[docker_hosts:children]
frontend
middleware
postgres
